### ISSUE TITLE
Parsing `align` and `offset` modifiers

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wat#34]
When I run a spec test that uses address modifiers I see the following error:

```
Error: unknown operator or unexpected token
     --> tests/spec_testsuite/proposals/simd/simd_load_splat.wast:14:87
      |
   14 |   (func (export "v8x16.offset0") (param $address i32) (result v128) (v8x16.load_splat offset=0 (local.get $address)))
      |                                                                                       ^
```

Using @alexcrichton's very handy `+nightly` and `RUST_BACKTRACE=1` trick, I believe this comes from a call to [`wast::parser::parse::<wast::Wast>`](https://github.com/bytecodealliance/wasmtime/blob/ec8144b87d42a82b254fc18762d1e1557d3e90f6/crates/wast/src/wast.rs#L160). Should this be working or is it just something we need to add to the parser?

**Comment by alexcrichton** [comment]
Oh whoops, I guess this wasn't exercised before or I forgot!

The fix is to update [these variants](https://github.com/bytecodealliance/wat/blob/1f445296f1738707503baed7cb26cd7c834800dc/crates/wast/src/ast/expr.rs#L656-L659) to have a `MemArg` argument [like so](https://github.com/bytecodealliance/wat/blob/1f445296f1738707503baed7cb26cd7c834800dc/crates/wast/src/ast/expr.rs#L479-L485) (I presume the default alignment here is 16 as well)
