### ISSUE TITLE
assert_invalid with non-parsable code

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wat#50]
The following has invalid wat code:

https://github.com/WebAssembly/testsuite/blob/master/proposals/simd/simd_load.wast#L189-L196

When I was working on https://github.com/bytecodealliance/wasmparser/pull/185, I was not able to skip the particular wast line with `assert_invalid`. Is it expected that content of assert_invalid parsed on-demand?

**Comment by alexcrichton** [comment]
Ah yeah this is expected unfortunately. The `assert_malformed` directive can handle invalid syntax, but `assert_invalid` is supposed to be a semantic error rather than a parse error.

The test was removed from upstream in https://github.com/WebAssembly/simd/commit/9352c9b788b59a3748b59bbeba5fd7f6b2b1cbec and the `testsuite` repo just hasn't been updated for that yet
